logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    useRedis: false
    redisConfig:
      host: 114.67.84.99
      port: 16379
    configs:
      - appId: wx7834dc191378a252
        secret: d122217936541f396454677c68579b03
        token: 5f6e779a4d1043dba588afee04985286 # 接口配置里的Token值
        aesKey: ZynfLkPjWQrPpnhJiy930XEXhr1N9iwI0nnWR3WBjSc # 接口配置里的EncodingAESKey值
